### ISSUE TITLE
Generalize JSONPath?

### ISSUE THREAD

**Issue by DazWilkin** [DazWilkin/akri-webhook#4]
Would it be possible to generalize the use of JSONPath such that multiple filters could be provided?

The challenge is that JSONPath is a filter mechanism but does not (!?) contain predicates.

We can do e.g.:

```console
{.spec.brokerPodSpec.containers[*].resources.limits}
{.spec.brokerPodSpec.protocol}
...
```

But would want e.g.:

Perhaps providing the filters as configuration to the Deployment too:

```YAML
        - name: webhook
          image: ghcr.io/dazwilkin/akri-webhook@...
          imagePullPolicy: Always
          args:
            - --filter="{.spec.brokerPodSpec.containers[*].resources.limits}"
            - --filter="{.spec.protocol.zeroconfg}"
            - --tls-crt-file=/secrets/tls.crt
            - --tls-key-file=/secrets/tls.key
            - --port=8443
            - --logtostderr
            - -v=2
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: SERVICE
```
