### ISSUE TITLE
Challenged with `certificates.k8s.io/v1`

### ISSUE THREAD

**Issue by DazWilkin** [DazWilkin/akri-webhook#5]
Struggling with `certificates.k8s.io/v1`

```YAML
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${SERVICE}.${NAMESPACE}
spec:
  groups:
  - system:authenticated
  request: $(cat ${FILENAME}.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/legacy-unknown
  usages:
  - digital signature
  - key encipherment
  - server auth
```

Without `signerName`, it errors:

```console
error: error validating "STDIN":
error validating data: ValidationError(CertificateSigningRequest.spec):
missing required field "signerName" in io.k8s.api.certificates.v1.CertificateSigningRequestSpec;
if you choose to ignore these errors, turn validation off with --validate=false
```

So, it's clear where the `signerName` goes and I was hoping to use `kubernetes.io/kubelet-serving` (see [docs](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers)) because, this one includes:

```console
Permitted key usages - exactly ["key encipherment", "digital signature", "server auth"].
```

Which matches the spec above (particularly `server auth`) but it doesn't work:

```bash
kubectl certificate approve ${SERVICE}.${NAMESPACE}
certificatesigningrequest.certificates.k8s.io/feriton.akri approved

kubectl get csr ${SERVICE}.${NAMESPACE}
NAME           AGE     SIGNERNAME                      REQUESTOR   CONDITION
feriton.akri   2m32s   kubernetes.io/kubelet-serving   admin       Approved,Failed
```

So, have reverted to `v1beta1` for the time being.
