### ISSUE TITLE
Lost original problem :-(

### ISSUE THREAD

**Issue by DazWilkin** [DazWilkin/akri-webhook#6]
/cc: @bfjelds

The new de|reserialization loses the solution to part of the original problem: https://github.com/deislabs/akri/issues/180

Namely, that the omission of `.brokerPodSpec.containers[*].resources` creates Instances without environment variables.

With the ValidatingAdmissionWebhookController applied:

```YAML
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: zeroconf
spec:
  protocol:
    zeroconf:
      kind: "_rust._tcp"
      port: 8888
      txtRecords:
        project: akri
        protocol: zeroconf
        component: avahi-publish
  capacity: 1
  brokerPodSpec:
    imagePullSecrets: # Container Registry secret
      - name: ghcr
    containers:
      - name: zeroconf-broker
        image: ghcr.io/dazwilkin/zeroconf-broker@sha256:993e5b8d....
#       resources:
#              limits: 
#                "{{PLACEHOLDER}}": "1"
```

Applying the above, creates 1 Instance:

```bash
kubectl get instances
NAME               CONFIG      SHARED   NODES      AGE
webthings-8bcaf2   webthings   true     ["akri"]   2s
```

But, the Pod will not work correctly and won't include environment variables:

```bash
INSTANCE=$(kubectl get instances --output=jsonpath="{.items[*].metadata.name}")

kubectl get pod/akri-${INSTANCE}-pod \
--output=jsonpath="{.spec.containers[*].resources}" | jq .
```

yields:

```JSON
{}
```

Whereas, including the `resources` section and reapplying:

```JSON
{
  "limits": {
    "akri.sh/webthings-8bcaf2": "1"
  },
  "requests": {
    "akri.sh/webthings-8bcaf2": "1"
  }
}
```

**Comment by bfjelds** [comment]
for me, i'm ok with someone omitting the resources.  though maybe that's a mistake ... perhaps we can warn if there are no containers with resources set (though omitting the brokerpodspec should be allowed).

my more pressing concern was to validate that people are getting what they ask for (to protect against yaml mistakes and misalignments) ... for example here, they put the resources at the wrong indentation level:

```yaml
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: zeroconf
spec:
  protocol:
    zeroconf:
      kind: "_rust._tcp"
      port: 8888
      txtRecords:
        project: akri
        protocol: zeroconf
        component: avahi-publish
  capacity: 1
  brokerPodSpec:
    imagePullSecrets: # Container Registry secret
      - name: ghcr
    containers:
      - name: zeroconf-broker
        image: ghcr.io/dazwilkin/zeroconf-broker@sha256:993e5b8d....
     resources:
       limits: 
         "{{PLACEHOLDER}}": "1"
```
